version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      API_KEY: ${API_KEY}
